# frozen_string_literal: true
source "https://rubygems.org"

gem 'action_dispatcher', git: 'https://github.com/codingstones/action_dispatcher'
gem 'jsonrpc', git: 'https://github.com/codingstones/jsonrpc'
gem 'socracan17', path: '../socracan17'

gem 'sinatra'
gem 'sinatra-contrib'
gem 'grape-entity'
gem 'rack-cors'
gem 'oj'

group :development do
  gem "bundler", "~> 1.14"
  gem "rake", "~> 10.0"
  gem "rspec", "~> 3.0"
  gem "rack-test", "~> 0.6"
end
